# Multiple Linear Regression

## Importing the libraries

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

pd.options.display.float_format = '{:.5f}'.format

## Importing the dataset and Splitting the training and test set


In [28]:
train_dataset = pd.read_csv('Train.csv')
test_dataset = pd.read_csv('Test.csv')

X_train = train_dataset.iloc[:, :-1].values
y_train = train_dataset.iloc[:, -1].values
X_test = test_dataset.iloc[:, :].values

In [29]:
print(X_train)

[[ 0.29 -0.95 -0.42  0.41  0.53]
 [-0.84 -0.19 -0.78 -1.05  0.6 ]
 [ 0.24  0.13 -0.15  0.7  -0.19]
 ...
 [ 1.04 -0.9   1.73 -1.87  0.44]
 [-1.27 -0.01  1.86 -1.08  0.74]
 [-1.88 -0.85 -1.45  0.49  1.46]]


In [30]:
print(y_train)

[ -82.15  -48.9    77.27 ... -107.51  -47.34 -115.94]


In [31]:
print(X_test)

[[ 1.02e+00  2.08e+00 -2.66e-01 -2.42e+00 -9.81e-01]
 [-3.75e-01  9.53e-01  6.27e-01  7.04e-01 -3.55e-01]
 [-1.02e+00  9.63e-01 -4.08e-01 -1.86e+00  4.55e-01]
 ...
 [ 5.55e-01  1.77e+00 -8.98e-01 -1.19e+00  3.41e-01]
 [-1.63e+00  8.56e-01 -5.66e-04  6.29e-01  4.53e-01]
 [ 1.39e-01  5.32e-01 -8.53e-01  3.17e-02  1.71e+00]]


## Training the Multiple Linear Regression model on the Training set

In [19]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [34]:
y_pred = regressor.predict(X_test)

print(y_pred.reshape(len(y_pred),1))

[[ 1.15e+02]
 [ 1.18e+02]
 [-2.17e+01]
 [-4.39e+01]
 [-9.59e+01]
 [-4.45e+01]
 [-7.56e+01]
 [ 2.38e+01]
 [ 1.74e+02]
 [ 1.73e+02]
 [-1.05e+02]
 [-2.08e+01]
 [-3.91e+00]
 [ 1.23e+02]
 [ 4.03e+01]
 [ 4.57e+01]
 [-1.90e+02]
 [ 2.26e+01]
 [ 1.16e+01]
 [ 1.36e+02]
 [ 6.49e+01]
 [-6.20e+01]
 [-1.08e+02]
 [-7.41e+00]
 [-5.85e+01]
 [ 1.19e+01]
 [ 2.92e+01]
 [ 1.08e+02]
 [ 2.41e+01]
 [-2.61e+01]
 [ 1.11e+02]
 [-4.49e+01]
 [ 2.17e+02]
 [-1.39e+01]
 [-2.29e+02]
 [ 1.55e+02]
 [-2.23e+00]
 [ 1.27e+01]
 [-3.08e+02]
 [ 7.71e+01]
 [-8.12e+01]
 [-2.07e+02]
 [-2.39e+02]
 [ 1.35e+02]
 [-7.38e+01]
 [ 1.05e+02]
 [-3.59e+00]
 [ 2.06e+01]
 [-9.80e+01]
 [-2.75e+01]
 [ 1.08e+01]
 [-1.74e+02]
 [ 6.52e+01]
 [-9.78e+01]
 [-1.06e+02]
 [-1.56e+02]
 [ 6.25e+01]
 [ 1.09e+02]
 [-7.46e+01]
 [ 4.17e+01]
 [ 4.12e+01]
 [-5.08e+01]
 [ 1.65e+02]
 [ 4.36e+01]
 [ 5.69e+01]
 [ 2.41e+01]
 [ 8.17e+01]
 [-1.80e+00]
 [-3.10e+00]
 [ 1.81e+00]
 [-2.39e+01]
 [ 1.62e+02]
 [-4.10e+01]
 [ 2.16e+01]
 [-6.64e+01]
 [-6.93e+01]
 [ 3.70e+01]