# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [7]:
dataset = pd.read_csv('CarPurchasingData.csv')
X = dataset.iloc[:, [3,4,5,6,7]].values
y = dataset.iloc[:, -1].values

In [8]:
print(X)

[[0.00000000e+00 4.18517198e+01 6.28120930e+04 1.16093809e+04
  2.38961250e+05]
 [0.00000000e+00 4.08706234e+01 6.66468929e+04 9.57295714e+03
  5.30973908e+05]
 [1.00000000e+00 4.31528975e+01 5.37985511e+04 1.11603551e+04
  6.38467177e+05]
 ...
 [1.00000000e+00 5.39434972e+01 6.88887780e+04 1.06116069e+04
  7.64531320e+05]
 [1.00000000e+00 5.91605086e+01 4.98119906e+04 1.40130345e+04
  3.37826638e+05]
 [1.00000000e+00 4.67311525e+01 6.13706777e+04 9.39134163e+03
  4.62946492e+05]]


In [9]:
print(y)

[35321.45877 45115.52566 42925.70921 67422.36313 55915.46248 56611.99784
 28925.70549 47434.98265 48013.6141  38189.50601 59045.51309 42288.81046
 28700.0334  49258.87571 49510.03356 53017.26723 41814.72067 43901.71244
 44633.99241 54827.52403 51130.95379 43402.31525 47240.86004 46635.49432
 45078.40193 44387.58412 37161.55393 49091.97185 58350.31809 43994.35972
 17584.56963 44650.36073 66363.89316 53489.46214 39810.34817 51612.14311
 38978.67458 10092.22509 35928.52404 54823.19221 45805.67186 41567.47033
 28031.20985 27815.73813 68678.4352  68925.09447 34215.7615  37843.46619
 37883.24231 48734.35708 27187.23914 63738.39065 48266.75516 46381.13111
 31978.9799  48100.29052 47380.91224 41425.00116 38147.81018 32737.80177
 37348.13737 47483.85316 49730.53339 40093.61981 42297.5062  52954.93121
 48104.11184 43680.91327 52707.96816 49392.8897  30841.00154 49373.37555
 41903.65171 45058.8969  52991.52667 50958.08115 41357.17897 44434.71917
 38502.42392 41221.24918 38399.46139 41456.68097 30

In [17]:
X = X.reshape(len(X),5)


## Splitting Into Training and Test Set

In [18]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [20]:
print(X_train)

[[ 0.98019606  0.4104977  -1.6619508  -0.64933159 -0.24462287]
 [-1.02020406  0.5448837   0.85586707 -0.93240467 -1.49187534]
 [-1.02020406  1.23781276 -0.38457054 -1.14202773 -0.0960339 ]
 ...
 [-1.02020406 -1.45388407  1.9018063   0.90404545 -1.06181584]
 [-1.02020406  0.60686745 -0.37735122 -2.12230328 -1.55376175]
 [-1.02020406 -0.7713426   0.78984347 -0.48138186 -0.06728634]]


In [22]:
print(y_train)

[[-0.87935776]
 [ 0.16848993]
 [ 0.49695953]
 [-0.83295546]
 [-1.41349565]
 [-0.62391323]
 [ 0.73691949]
 [ 0.27610647]
 [ 1.7736841 ]
 [-1.14146817]
 [ 0.80861937]
 [ 0.3158527 ]
 [-0.43388983]
 [ 0.36991506]
 [ 0.65327469]
 [-0.80158534]
 [ 1.08814305]
 [ 1.2526457 ]
 [ 1.03442917]
 [ 1.57070988]
 [-1.12050016]
 [ 0.43725512]
 [-1.02053968]
 [ 0.45795028]
 [-0.96120007]
 [ 0.03555853]
 [-1.05732602]
 [ 0.02872784]
 [ 0.36591186]
 [ 0.21938971]
 [ 0.31667132]
 [-0.19089914]
 [-0.12210187]
 [ 0.37801337]
 [ 0.06372127]
 [-0.25244513]
 [-0.36926774]
 [ 0.16538912]
 [-3.27518294]
 [-0.42345637]
 [ 1.13752893]
 [ 0.3935664 ]
 [ 0.83500858]
 [-0.64400851]
 [-0.19338213]
 [ 1.10819611]
 [-0.41559742]
 [ 0.12257828]
 [-0.92635052]
 [ 1.17327441]
 [-1.3667683 ]
 [-0.74080959]
 [ 0.42681919]
 [ 0.3462816 ]
 [ 1.43527327]
 [ 0.29771554]
 [ 0.80851531]
 [ 0.66117259]
 [ 1.54281354]
 [ 0.50972768]
 [-0.76078924]
 [-1.53498119]
 [-0.16414911]
 [-1.35601994]
 [ 0.03534675]
 [-0.24270862]
 [-0.07584

## Training the SVR model on the whole dataset

In [23]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

/Applications/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting a new result

In [24]:
sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))

array([39280.31907346, 43112.39098175, 30379.90231924, 51573.7418035 ,
       38566.7408831 , 54043.13719608, 60385.00843035, 60988.30856627,
       37077.7591796 , 30468.93423759, 47356.81019797, 57774.5992882 ,
       52634.55203083, 60040.22741782, 28606.6482053 , 30865.52916678,
       48256.61212365, 59546.24386495, 42186.68881428, 23729.15434115,
       49027.57940415, 36874.16894875, 46419.58480769, 27806.05707539,
       65736.34773625, 43734.10267225, 43205.49025029, 47272.78200186,
       58699.62593896, 59890.1164257 , 48487.58657972, 42517.96264965,
       55867.59936602, 42969.66250966, 63119.4316256 , 61421.70498833,
       34551.98169487, 60081.96334542, 42538.09535668, 42207.00113197,
       59992.57159988, 33237.64441612, 30578.98441698, 41296.13012849,
       41158.63223551, 45003.84084835, 44767.07393843, 54558.62585992,
       36435.3337102 , 34325.03653468, 37310.61939479, 40599.51539988,
       50777.46233482, 53083.08639304, 39233.89884413, 27616.94811433,
      

In [26]:
print(y_test)

[[38955.21919]
 [43401.56612]
 [29417.64694]
 [52150.41786]
 [38243.06228]
 [53017.26723]
 [60526.97788]
 [59538.40327]
 [37714.31659]
 [31300.54347]
 [46846.7305 ]
 [56973.18105]
 [53993.44322]
 [70878.29664]
 [27889.95197]
 [31526.04931]
 [47979.48549]
 [58667.06865]
 [42369.64247]
 [10092.22509]
 [48518.90163]
 [37183.10293]
 [46325.50959]
 [27586.71854]
 [68925.09447]
 [43898.2733 ]
 [43402.31525]
 [46710.52519]
 [61593.52058]
 [58235.41454]
 [48516.84335]
 [42592.88647]
 [54755.42038]
 [42774.35579]
 [63079.84329]
 [60117.67886]
 [35716.31133]
 [59984.16361]
 [42793.9932 ]
 [42997.16761]
 [59625.02618]
 [34215.7615 ]
 [30419.8    ]
 [37303.56701]
 [41357.17897]
 [45115.52566]
 [44577.44829]
 [53496.48183]
 [38174.87433]
 [33640.73697]
 [35726.95299]
 [41026.02421]
 [50188.86612]
 [53655.53859]
 [39766.64804]
 [28700.0334 ]
 [43503.97349]
 [57430.76903]
 [45509.69732]
 [59096.26978]
 [38502.42392]
 [48025.02542]
 [42704.3221 ]
 [47719.47741]
 [42321.56548]
 [49721.31082]
 [59045.51